name: Build Plugins

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build
        run: dotnet build src

      - name: Test
        run: dotnet test src
